# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "aiq-backend-state"
    dynamodb_table = "aiq-backend-state"
    encrypt        = true
    key            = "networking/terraform.tfstate"
    profile        = "aiq-infra"
    region         = "eu-west-1"
  }
}
