{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aiq-app.fullname" . }}
  labels:
    {{- include "aiq-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minReplicas | default 1 }}
  selector:
    matchLabels:
      {{- include "aiq-app.selectorLabels" . | nindent 6 }}
{{- end }}
