{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiq-app.fullname" . }}
  labels:
    {{- include "aiq-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback,post-delete
data:
{{- range $key, $secret := .Values.secrets }}
  {{- if kindIs "string" $secret }}
    {{ $key }}: {{ $secret | b64enc }}
  {{- else }}
    {{ $key }}: {{ toJson $secret | b64enc }}
  {{- end -}}
{{ end }}
type: Opaque
{{ end }}
